### ISSUE TITLE
Discuss language for package arguments

### ISSUE THREAD

**Issue by edwardsmarc** [beaconsproject/beaconstools#3]
e.g. benchmarks vs networks vs reserves - do we use general language like 'reserves', or BEACONs specific language like 'benchmarks'.

Proposal - use 'reserve' instead of 'benchmark'. 
Use 'reserve network' for multiple reserves.

Change function names to use reserve instead of benchmark.

Create an issue for builder. Do we change the name of the benchmarkbuilder package?

**Comment by edwardsmarc** [comment]
Does IUCN have any guidance for naming 'reserves'.

**Comment by edwardsmarc** [comment]
IUCN use the term 'reserve' for **Category 1a - strict nature reserves**. This fits under the umbrella term **protected areas** which includes all categories.

Our tools do not need to be restricted to strict nature reserves, so under the IUCN terminology, protected areas would probably be the language to use (in place of benchmarks or reserves).

We could use **pa** for any functions or arguments that currently use **benchmark**.
- benchmarks_to_networks() ---> pas_to_networks()
- benchmark_table ----> pa_table

The name of the builder package could be changed from:
- benchmarkbuilder ----> pabuilder

Or we simply name the packages:
- beaconstools
- beaconsbuilder

**Comment by klisgo** [comment]
I like the use of "protected area" given the IUCN definition of Protected Area:  “a clearly defined geographical space, recognized, dedicated, and managed through legal or other effective means, to achieve the long-term conservation of nature with associated ecosystem services and cultural values” (Dudley 2008)

Dudley, N (eds.). 2008. Guidelines for Applying Protected Area Management Categories. Gland, Switzerland, IUCN. 86. p. Available online: https://portals.iucn.org/library/sites/library/files/documents/pag-021.pdf

**Comment by edwardsmarc** [comment]
FS suggested 'conservation areas'. Some issues with 'protected areas' that caused the initial avoidance of the term in favor of 'benchmarks'.

**Comment by MelinaHoule** [comment]
I don't know if the meaning is the same in english, but in french I would have proposed "conservation refuges"  instead of conservation areas because it involves different environmental factors and a reduce level of disturbance which is exactly what builder uses. But I'm not sure if the meaning of refuges is exactly the same between languages.

**Comment by edwardsmarc** [comment]
All cases of 'protected area' should be searched and replaced with 'conservation area' in the docs.
