### ISSUE TITLE
Code review - warning message when knitting vignette overview

### ISSUE THREAD

**Issue by MelinaHoule** [beaconsproject/beaconstools#53]
To generate the overview.html, I knitted the overview.Rmd file and received that warning:

Warning message:
The vignette title specified in \VignetteIndexEntry{} is different from the title in the YAML metadata. The former is "overview", and the latter is "Using beaconstools to rank reserves". If that is intentional, you may set options(rmarkdown.html_vignette.check_title = FALSE) to suppress this check.

Since it is intentional, should we set the option vignette.check title=FALSE as propsed?

**Comment by edwardsmarc** [comment]
I got this warning in the builder package too. I'll fix it.
