### ISSUE TITLE
code review - calc_dissimilarity()

### ISSUE THREAD

**Issue by MelinaHoule** [beaconsproject/beaconstools#55]
When running the function calc_dissimilarity(), **block i on n** is used as a kind of progress bar. What defines a block and what is it for?

**Comment by edwardsmarc** [comment]
The function splits the polygons into groups (or blocks) and runs one at a time. I could change it so lists the actual number of polygons being processed (e.g. 100 of 1500), or we could remove the message all together. I like to have the progress message in functions that take a long time so the user knows its running. But maybe it's necessary.

**Comment by MelinaHoule** [comment]
I like your idea of having the number of polygon being process instead of block. The block results from a grouping strategy which is not explain.
